config/routes.rb
Surfbuddy::Application.routes.draw do
  
  get "sessions/new"
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#login', as: 'login'  
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get '/auth/:provider/callback', to: 'sessions#create'

  root to: 'sessions#login'
  
  resources :users do 
    resources :messages
  end

  resources :sessions
  resources :posts
  resources :comments
  resources :conditions
  

end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id           :integer          not null, primary key
#  recipient_id :integer
#  sender_id    :integer
#  body         :text
#  created_at   :datetime
#  updated_at   :datetime
#

class Message < ActiveRecord::Base
  
  belongs_to :recipient, :class_name => 'User'
  belongs_to :sender, :class_name => 'User'
  belongs_to :user
  
  attr_accessible :recipient_id, :sender_id, :body, :title

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include SessionsHelper
  before_filter :signed_in_user, except: [:new, :create]

  def index
    @user = User.find(params[:user_id])
    @messages = @user.received_messages
  end

  def new
    @message = Message.new
    @user = User.find(params[:user_id])
  end

  def create
    @message = Message.new(params[:message])
    @message.sender = current_user
    @message.recipient_id = params[:user_id]
    @message.save
    redirect_to user_messages_path
  end  

  def show
    @message = Message.find(params[:id])
    sender = User.find(@message.sender_id)
    @profile = sender.profile
  end

end

app/views/messages/index.html.erb
<h3>Your Messages</h3>


<div class="message_feed">
    <% @messages.reverse.each do |message| %>
  <div class="messages">
    <h4 class="subheader"><%= message.created_at.strftime('%b %e %Y %l:%M %P') %></h4>

    <h3 class="title"><small>From: <%=link_to message.sender.name, message.sender%></small></h3>
    <h3><small><%= message.title.capitalize %></small></h3> 
    <p><%= message.body.capitalize %></p>
    <%= link_to 'Reply', new_user_message_path(message.sender.id)  %>
  </div>
    <%end%>
</div>

app/views/messages/new.html.erb
<h3>Send a Message </h3>

<%= form_for [@user, @message] do |f| %>
<%= f.label :title %>
<%= f.text_field :title %> </br>

<%= f.label "message" %>
<%= f.text_area :body, :rows => "30" %>

<%= f.submit "Send Message" %>
<%end%>