config/routes.rb
Surfbuddy::Application.routes.draw do
  
  get "sessions/new"
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#login', as: 'login'  
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get '/auth/:provider/callback', to: 'sessions#create'

  root to: 'sessions#login'
  
  resources :users do 
    resources :messages
  end

  resources :sessions
  resources :posts
  resources :comments
  resources :conditions
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Surf Buddy" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="http://cdn.oesmith.co.uk/morris-0.4.3.min.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="http://cdn.oesmith.co.uk/morris-0.4.3.min.js"></script>
  </head>


  <body>
    <nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "SurfBuddy", root_url %></a></h1>
    </li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <li class="divider"></li>
      <li><%= link_to "Posts", posts_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Condition Reports", conditions_path %></li>
      <li class="divider"></li>
      <% if current_user%>
      <li><%= link_to "Messages", user_messages_path(current_user.id) %></li> 
      <li class="divider"></li>
      <li><%= link_to "Profile", current_user %></li>
      <% end %>
    </ul>
  </div>
</nav>


<div id="image" class="row">
  <div class="small-6 large-2 columns"></div>
  <div class="small-6 large-8 columns"><%= yield %></div>
  <div class="small-12 large-2 columns">   
    <% if current_user %>
    Logged in as <%= current_user.email %>
    <%= link_to "Log Out", session_path("current"), method: 'delete' %>
    <% else %>
    <%= link_to "Sign Up", new_user_path %> or
    <%= link_to "Sign In", root_url %>
    <% end %></div>
</div>

    

    
  <%= javascript_include_tag "application" %>
    
    
  </body>
</html>

app/views/layouts/conditions.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Surf Buddy" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="http://cdn.oesmith.co.uk/morris-0.4.3.min.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="http://cdn.oesmith.co.uk/morris-0.4.3.min.js"></script>
  </head>


  <body>
    <nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "SurfBuddy", root_url %></a></h1>
    </li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <li class="divider"></li>
      <li><%= link_to "Posts", posts_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Condition Reports", conditions_path %></li>
      <li class="divider"></li>
      <% if !current_user.nil? %>
      <li><%= link_to "Messages", user_messages_path(current_user.id) %></li> 
      <% end %>
      <li class="divider"></li>
      <li><%= link_to "Profile", current_user %></li>
    </ul>
  </div>
</nav>
<div class="row">
  <div class="small-6 large-2 columns"></div>
  <div class="small-6 large-8 columns"></div>
  <div id="conditions_signin" class="small-12 large-2 columns">
    <% if current_user %>
    Logged in as <%= current_user.email %>
    <%= link_to "Log Out", session_path("current"), method: 'delete' %>
    <% else %>
    <%= link_to "Sign Up", new_user_path %> or
    <%= link_to "Sign In", root_url %>
    <% end %>
  </div>  
</div>

<%= yield %>

<%= javascript_include_tag "application" %>
    
    
  </body>
</html>